In [8]:
import numpy as np

x = np.ones([1,2,2,1])
print("x:\n",x)

y = np.pad(
    x,
    pad_width=((0, 0), (0, 0), (1, 2), (3, 4)),
    mode='constant',
    constant_values=0,
)

print("y:\n",y)

print("y.shape:",y.shape)




x:
 [[[[1.]
   [1.]]

  [[1.]
   [1.]]]]
y:
 [[[[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 1. 0. 0. 0. 0.]
   [0. 0. 0. 1. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 1. 0. 0. 0. 0.]
   [0. 0. 0. 1. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]]]
y.shape: (1, 2, 5, 8)


 对 （1,2）（3,4）的理解(上下 左右) 就是 在 0 0 的 上方加 1 行 数值都是 constant 1.2 ，下方 加两行，左边加 3行 右边 加 4 行

In [1]:
import onnx

node = onnx.helper.make_node(
    'Pad',
    inputs=['x'],
    outputs=['y'],
    mode='constant',
    value=1.2,
    pads=[0, 0, 1, 3, 0, 0, 2, 4],
)
# 1 上 3 左  2 下 4  右
print(node)

input: "x"
output: "y"
op_type: "Pad"
attribute {
  name: "mode"
  s: "constant"
  type: STRING
}
attribute {
  name: "pads"
  ints: 0
  ints: 0
  ints: 1
  ints: 3
  ints: 0
  ints: 0
  ints: 2
  ints: 4
  type: INTS
}
attribute {
  name: "value"
  f: 1.2000000476837158
  type: FLOAT
}



In [4]:
import numpy as np

x = np.zeros([1,2,2,2])
print("x:\n",x)

y = np.pad(
    x,
    pad_width=((1, 1), (1, 1), (0,0), (0, 0)),
    mode='constant',
    constant_values=1.2,
)

print("y:\n",y)

x:
 [[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
y:
 [[[[1.2 1.2]
   [1.2 1.2]]

  [[1.2 1.2]
   [1.2 1.2]]

  [[1.2 1.2]
   [1.2 1.2]]

  [[1.2 1.2]
   [1.2 1.2]]]


 [[[1.2 1.2]
   [1.2 1.2]]

  [[0.  0. ]
   [0.  0. ]]

  [[0.  0. ]
   [0.  0. ]]

  [[1.2 1.2]
   [1.2 1.2]]]


 [[[1.2 1.2]
   [1.2 1.2]]

  [[1.2 1.2]
   [1.2 1.2]]

  [[1.2 1.2]
   [1.2 1.2]]

  [[1.2 1.2]
   [1.2 1.2]]]]


In [14]:

import tensorflow as tf
 
a=tf.constant([
        [[1.0,2.0,3.0,4.0],
        [5.0,6.0,7.0,8.0],
        [9.0,10.0,11.0,12.0],
        [13.0,14.0,15.0,16.0]]

    ])
 
a=tf.reshape(a,[1,4,4,1])
 
pooling=tf.nn.max_pool(a,[1,2,2,1],[1,2,2,1],padding='VALID')
with tf.Session() as sess:
    print("image:")
    image=sess.run(a)
    print (image)
    print("reslut:")
    result=sess.run(pooling)
    print (result)

image:
[[[[ 1.]
   [ 2.]
   [ 3.]
   [ 4.]]

  [[ 5.]
   [ 6.]
   [ 7.]
   [ 8.]]

  [[ 9.]
   [10.]
   [11.]
   [12.]]

  [[13.]
   [14.]
   [15.]
   [16.]]]]
reslut:
[[[[ 6.]
   [ 8.]]

  [[14.]
   [16.]]]]


In [16]:

import tensorflow as tf
 
X=tf.constant([
        [[1.0,2.0,3.0,4.0],
        [5.0,6.0,7.0,8.0],
        [9.0,10.0,11.0,12.0],
        [13.0,14.0,15.0,16.0]]

    ])
X=tf.reshape(X,[1,4,4,1])
 
pooling1=tf.nn.max_pool(X,[1,1,1,1],[1,2,2,1],padding='SAME')
with tf.Session() as sess:
    print("image:")
    image1=sess.run(X)
    print (image1)
    print("reslut:")
    result1=sess.run(pooling1)
    print (result1)


image:
[[[[ 1.]
   [ 2.]
   [ 3.]
   [ 4.]]

  [[ 5.]
   [ 6.]
   [ 7.]
   [ 8.]]

  [[ 9.]
   [10.]
   [11.]
   [12.]]

  [[13.]
   [14.]
   [15.]
   [16.]]]]
reslut:
[[[[ 1.]
   [ 3.]]

  [[ 9.]
   [11.]]]]


In [3]:
import numpy as np
x = np.array( [[0, 0],[3, 3],[3, 3],[0, 0]])
print(x)

[[0 0]
 [3 3]
 [3 3]
 [0 0]]


In [4]:
x.transpose()


array([[0, 3, 3, 0],
       [0, 3, 3, 0]])

In [6]:
x.transpose().reshape((1,8))

array([[0, 3, 3, 0, 0, 3, 3, 0]])