In [9]:
import tensorflow as tf
import numpy as np

x1 = np.random.randn(1, 224, 224, 3).astype(np.float32)

x_val = np.array(x1, dtype=np.float32)
print(x_val.shape)

x = tf.placeholder(tf.float32, x_val.shape, name="input")

print(x.get_shape())

pad = [[0, 0], [3, 3], [3, 3], [0, 0]]

paddings = tf.constant(pad)

print("paddings.shape:", paddings.get_shape())
op = tf.pad(x, paddings, "CONSTANT")

output = tf.identity(op, name="output")

print("output :", output.get_shape())

(1, 224, 224, 3)
(1, 224, 224, 3)
paddings.shape: (4, 2)
output : (1, 230, 230, 3)


In [23]:
import tensorflow as tf
import numpy as np

x1 = np.random.randn(1, 224, 224, 3).astype(np.float32)

x_val = np.array(x1, dtype=np.float32)
print(x_val.shape)

x = tf.placeholder(tf.float32, x_val.shape, name="input")

print(x.get_shape())

pad = [[0, 0], [3, 3], [3, 3], [0, 0]]

paddings = tf.constant(pad)

print("paddings.shape:", paddings.get_shape())
op = tf.pad(x, paddings, "CONSTANT")

output = tf.identity(op, name="output")

print("output :", output.get_shape())

(1, 224, 224, 3)
(1, 224, 224, 3)
paddings.shape: (4, 2)
output : (1, 230, 230, 3)


In [25]:
#x = np.random.randn(1, 224, 224, 3).astype(np.float32)
x = np.random.randn(1, 4, 4, 3).astype(np.float32)

y = np.pad(
    x,
    pad_width=((0, 0), (1, 1), (1, 1), (0, 0)),
    mode='constant',
    constant_values=0,
)

print("y.shape:", y.shape)
print(y)

y.shape: (1, 6, 6, 3)
[[[[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [-1.0232489   2.7595384   0.8121258 ]
   [-1.6652445  -0.6384244  -0.22878201]
   [-0.61304355 -0.16056004 -0.3214093 ]
   [-0.04380637  0.63261026  0.16894554]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 1.6818326  -0.6412685  -0.7122386 ]
   [ 0.7978569  -0.6242278   0.14693917]
   [-1.3299435   0.08197591  1.9537549 ]
   [-0.39338037  2.1700249   0.48503923]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 1.7550678  -1.522111   -0.13694838]
   [ 0.4294414   0.10864529 -0.9327744 ]
   [-0.32780212  0.72184706 -0.12752706]
   [ 0.44695127 -0.42628846 -0.540092  ]
   [ 0.          0.          